### ISSUE TITLE
generic JS for our flickr widget is causing JS errors on pages not using widget

### ISSUE THREAD

**Issue by mandythomas** [chapmanu/cascade-assets#107]
From Ed Lan. This code is in the master.js file embedded in all www and webfarm pages but the e.query.results.feed can be a null value, so that needs to be checked before the rest of the code can proceed.
      , l = function(e) {
        var t = n.find("ul")
          , i = u(t, e);
        if (i) {
            var a = e.query.results.feed.link[0].href
              , s = a.split("userid=")[1].split("&")[0];
            n.find(".more-link").attr("href", "https://www.flickr.com/groups/" + s)
        }

Ed's test page on webfarm is https://webfarmtest.chapman.edu/TestWebSite/ but can see same JS errors listed in browser for any www page

**Comment by tatwell** [comment]
@mandythomas Are these the errors Ed is referring to?

![feed-errors](https://cloud.githubusercontent.com/assets/12798918/20725761/c0a23204-b627-11e6-941d-89c8ea823b6f.png)

Technically these are warnings, which I think our code deliberately emits. The distinction is significant because unlike errors, I don't believe they stop further execution of javascript on page.

In any event, we should fix this. The feeds should be called only on pages displaying the widget. But this might make issue a little less urgent.

**Comment by tatwell** [comment]
Add Trello card:

- https://trello.com/c/R9oC7wUj/146-defect-in-cascade-asset-code-flickr-widget-is-making-ajax-calls-even-on-pages-where-not-displayed

**Comment by tatwell** [comment]
Fixed here:

- https://github.com/chapmanu/cascade-assets/commit/547fc77e161a038a1a45fb58af993f2ac2aa910e

**Comment by tatwell** [comment]
Successfully deployed to production.
