### ISSUE TITLE
mixed-content warning in Chrome (coming from omniNav)

### ISSUE THREAD

**Issue by mandythomas** [chapmanu/cascade-assets#108]
From Ed Lan.

On line 303 of /_cascade/formats/Omni-Nav, you have:

<form action="${domain}search-results/index.aspx">

where $domain = "http://www.chapman.edu/"

is causing a mixed-content warning in Chrome.  If you change $domain = "https://www.chapman.edu/" the warning should go away.

Also the website is loading flashplayer.swf, do we still need to use flash on the website?

**Comment by tatwell** [comment]
Trello card: https://trello.com/c/eH4GyTDa/156-defect-omni-nav-raises-a-mixed-content-warning-in-chrome

**Comment by tatwell** [comment]
@mandythomas I can't locate `flashplayer.swf` in dev home page source:

https://dev-www.chapman.edu/index.aspx

Any ideas where that's located?

I fixed the domain.

**Comment by tatwell** [comment]
@mandythomas Responding to your [Trello comment](https://trello.com/c/eH4GyTDa/156-defect-omni-nav-raises-a-mixed-content-warning-in-chrome#comment-584f144875ed650c2c970d74) here. Prefer to keep info on issues in Github.

Your comment inspired me to search for `swf` in our codebase. I found a couple likely culprits (these are likely where the `master.js` references you are seeing come from):

- [app/assets/javascripts/cascade/plugins/swf-object.js](https://github.com/chapmanu/cascade-assets/blob/development/app/assets/javascripts/cascade/plugins/swf-object.js)
- [app/assets/javascripts/cascade/video-overlay.js](https://github.com/chapmanu/cascade-assets/blob/development/app/assets/javascripts/cascade/video-overlay.js#L15)

I'm hesitant to remove anything because I don't know if these are required to display videos to our users or how their absence will affect users on older devices. I'm guessing modern browsers don't require them but I really don't know. I'll do a bit of Googling and see what turns up.

**Comment by tatwell** [comment]
`swf-object.js` comes from this repo, which is no longer supported:

- https://github.com/swfobject/swfobject

So I propose removing that file and removing the Flash Player check from `video-overlay.js`.

**Comment by tatwell** [comment]
Regarding `swf-object.js`, this StackOverflow is relevant:

http://stackoverflow.com/questions/40158579/is-swfobject-js-still-needed-in-html5-for-swf-files

**Comment by tatwell** [comment]
I [removed `swf-object.js` code](https://github.com/chapmanu/cascade-assets/commit/fedc926195f10e1a2a90fb0dc1f5d5a728ba7683) and tested the home page locally in Chrome and Firefox. I did not find any issue with videos and the outdated Flash Player warning no longer appears in Firefox.

I will deploy to Dev Cascade and ask product owners to review.

**Comment by tatwell** [comment]
Successfully deployed.
