### ISSUE TITLE
events listing in News Events widget of 2/3 Column Modular templates is not loading

### ISSUE THREAD

**Issue by mandythomas** [chapmanu/cascade-assets#160]
The events listing within the News/Events widget in 2/3 Column Modular templates is not working on most pages. One where it works is http://www.chapman.edu/dodge/student-life/index.aspx. One where it doesn't is http://www.chapman.edu/business/argyros-alumni/index.aspx. 

It uses rss feeds from events.chapman.edu and in particular the category field for the date of the event. The category and pubdate fields both contain the event date. Category is being parsed in the news-events.js javascript to pull out parts of the date. However recently additional category nodes are appearing in the rss feed for any given event and they contain info about buildings, not a date, so the function is failing. See https://events.chapman.edu/events.rss?group_id=11%2C73%2C29%2C92%2C31%2C163%2C10

Need to figure out why extra category nodes are in the rss now, OR use the pubdate instead of category field in the javascripts\cascade\level\news-events.js function, however there was a note in javascript function saying "pubdate sometimes contained original but not current event date; use category field instead". Need to verify if that's still true or safe to use. Also note the dates are formatted differently in pubdate vs category nodes.

**Comment by tatwell** [comment]
Trello card: https://trello.com/c/tej9kISv/

- Examples
  - Failing: https://www.chapman.edu/events/homecoming-weekend/index.aspx
  - Working: https://www.chapman.edu/dodge/student-life/index.aspx

Also, loading image broken and needs to be fixed:

    <img alt="Loading events list..." class="loading" src="../_files/level/img/ajax-loader.gif">

**Comment by tatwell** [comment]
Events widget source:

- /_cascade/formats/modular/widgets/Featured News Events Left Col

**Comment by tatwell** [comment]
I think I've identified the source of the issue. Not sure why yet it's happening.

I've reproduced the issue here:
- http://localhost:3000/modular/two_column

When I load that page, I see the following error in the console:
```
Uncaught TypeError: rssitem.category.split is not a function
```

I added a debug statement to report the data that was returned from the Yahoo API feed:
```
//query.yahooapis.com/v1/public/yql?q=select%20*%20from%20rss(3)%20where%20url%3D'http://www.chapman.edu/getFeed.ashx?name=events'&format=json&diagnostics=true&callback=?
```

The data includes 3 `data.query.results.item` objects. Here is what it reports for each `category` element:

- `["2017/03/06 (Mon)", "WALLACE ALL FAITHS CHAPEL"]` (Array)
- `["2017/03/06 (Mon)", "AF 209ABC"]` (Array)
- `"2017/03/06 (Mon)"` (String)

It appears code expects a string. See:

- https://github.com/chapmanu/cascade-assets/blob/development/app/assets/javascripts/cascade/level/news-events.js#L230

The problem is the feed provides 2 category tags for some events. See:

- http://www.chapman.edu/getFeed.ashx?name=events

The solution? One of the following:

1. Fix feed so it include one one category element with datetime value.
2. Add some code to feed `news-events.js` to check category value type and handle appropriately.

Plan to use option #2.

**Comment by mandythomas** [comment]
I agree, option 2 sounds good. The extra category node is a new thing. Never was multiple in there until very recently so not sure what changed on events.chapman.edu. Was only ever one and only contained date. Did you see my issue writeup at https://github.com/chapmanu/cascade-assets/issues/160

**Comment by tatwell** [comment]
@mandythomas Yes, your writeup is at top. That's where I started. Thanks for opening issue.

**Comment by tatwell** [comment]
Fix here (mislabeled issue in comment):

https://github.com/chapmanu/cascade-assets/commit/072df4de9071a6069ab9592f4a529f7a42708930

**Comment by tatwell** [comment]
Released to production.
