### ISSUE TITLE
In Cascade / WWW, stories feed fails to pull stories from new Blogs career feed.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/cascade-assets#261]
Trello Card: https://trello.com/c/VRqeHMKz

This page on dev:

- https://dev-www.chapman.edu/campus-services/marketing-communication/guidelines-and-resources/web/1-column-modular-example-page.aspx

is currently pointed at this feed:

- https://blogs.chapman.edu/feed/career

However, it does not display any stories from the feed (they should be above the red "View more stories" button:

![screen shot 2017-10-11 at 9 35 03 am](https://user-images.githubusercontent.com/12798918/31453569-82969296-ae67-11e7-9abd-9205613befe8.png)

The console in Chrome shows that it is actually trying to pull data from this URL, which is blank:

- https://social.chapman.edu/feed?source=https%3A%2F%2Fblogs.chapman.edu%2Ffeed%2Fcareer&service=wordpress&per=4&source=https%3A%2F%2Fblogs.chapman.edu%2Ffeed%2Fcareer&service=wordpress&per=4

So it could be an issue with the widget javascript in Cascade or in Social or maybe even the Blogs feed itself.

**Comment by tatwell** [comment]
Question: how is Social instructed to start collecting posts from a Blogs feed?

**Comment by mirabelrice** [comment]
### Issue Fixed
Inside expected the `source` param in the url to be a specific blog site, for example: https://blogs.chapman.edu/happenings/. In Inside, a `Post` record `belongs_to` a `Source` record and for blogs `source.external_url` is the url of the blog site. Since https://blogs.chapman.edu/feed/career doesn't match any `source.external_url` in the inside database, it was returning no results.

It actually turns out we may not have needed to create a feed on blogs in the first place, because Inside associates blog tags with `Keywords`. 
The url https://social.chapman.edu/feed?service=wordpress&keyword=career returns blog posts tagged as "career".

I adjusted the stories feed JS to accept social.chapman urls as well as blog urls. The stories feed now returns "career" tagged stories.
![screen shot 2017-11-07 at 9 32 12 am](https://user-images.githubusercontent.com/11791136/32508408-112f17c0-c39f-11e7-80bf-e4d1fad78b62.png)

This will also work for any future need to filter the stories feed by tag.
