### ISSUE TITLE
On Law home page, buttons in mobile footer do not function.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/cascade-assets#99]
This is visible in production right now. See footer for this page in mobile format:

http://www.chapman.edu/law/index.aspx

**Comment by tatwell** [comment]
Created defect in Trello: 

- https://trello.com/c/iBQyptfs/145-defect-on-law-home-page-buttons-in-mobile-footer-are-not-working

**Comment by tatwell** [comment]
This issue is expected to be resolved by Mandy's updates. For details see [this comment](https://trello.com/c/iBQyptfs/145-defect-on-law-home-page-buttons-in-mobile-footer-are-not-working#comment-583dca4764b32a6f41602415).

**Comment by tatwell** [comment]
@mandythomas I am going to reopen this since it is still technically an issue. Do you have a Trello card that you can link here so that we can track it?

**Comment by kaylaziegler** [comment]
I'm not seeing this issue anywhere in production anymore: http://www.chapman.edu/law/index.aspx

Not sure if I'm not understanding what the issue is, but everything seems to be functioning as expected on the mobile law homepage. We can reopen this if someone is able to replicate it and brings it to our attention.
